tap "homebrew/bundle"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# File comparison utilities
brew "diffutils"
# Load/unload environment variables based on $PWD
brew "direnv"
# Bash, Zsh and Fish completion for Docker
brew "docker-completion"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# GitHub command-line tool
brew "gh"
# Remote repository management made easy
brew "ghq"
# Upload multiple artifacts to GitHub Release in parallel
brew "ghr"
# Distributed revision control system
brew "git"
# Prevents you from committing sensitive information to a git repo
brew "git-secrets"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# GNU grep, egrep and fgrep
brew "grep"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Easy way to access the system keyring service from python
brew "keyring"
# Run local Kubernetes cluster in Docker
brew "kind"
# Simple terminal UI for git commands
brew "lazygit"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Interactive cheatsheet tool for the command-line
brew "navi"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Network Kanji code conversion Filter (NKF)
brew "nkf"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Fast, configurable, shell plugin manager
brew "sheldon"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Cross-shell prompt for astronauts
brew "starship"
# Terminal multiplexer
brew "tmux"
# Vi 'workalike' with many additional features
brew "vim"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# UNIX shell (command interpreter)
brew "zsh"
# GPU-accelerated terminal emulator
cask "alacritty"
# Chromium based browser
cask "arc"
# App for managing battery charging. (Also installs a CLI on first use.)
cask "battery"
# Tool to customise input devices and automate computer systems
cask "bettertouchtool"
# Write, edit, and chat about your code with AI
cask "cursor"
cask "font-udev-gothic-nf"
# Web browser
cask "google-chrome"
# Japanese input software
cask "google-japanese-ime"
# Keymap tool for Happy Hacking Keyboard Professional (Hybrid models only)
cask "hhkb-keymap-tool"
# Software for Logitech devices
cask "logi-options+"
# Replacement for Docker Desktop
cask "orbstack"
# Collaboration platform for API development
cask "postman"
# Control your tools with a few keystrokes
cask "raycast"
# Open-source code editor
cask "visual-studio-code"
