name: Nix build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-nix-application:
    runs-on: macOS-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@bafaa638b9d5ec0e7e3ac1a7fc80453ef1fd265f # v3.20.0
      - name: Build home configuration
        run: nix run nixpkgs#home-manager -- build --flake .#runner
      - name: Build darwin configuration
        run: nix run nix-darwin -- build --flake .#runner
